name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-03"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnowdb"
database_id = "2c01f183-556a-4b97-a43e-348e0468247b"
